name: Code Quality

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 flake8-bugbear PyYAML
        
    - name: AutoPkg Code Style Requirements
      run: |
        echo "=== AutoPkg Code Style Validation ==="
        echo "AutoPkg requires: black, isort, and flake8 with bugbear"
        echo ""
        
    - name: Check Python formatting (black)
      run: |
        echo "Checking black formatting..."
        black --check --diff FleetGitOpsUploader/FleetGitOpsUploader.py
        echo "✅ Black formatting passed"
        
    - name: Check import sorting (isort)
      run: |
        echo "Checking import order..."
        isort --check-only --diff FleetGitOpsUploader/FleetGitOpsUploader.py
        echo "✅ Import sorting passed"
        
    - name: Check flake8 with bugbear
      run: |
        echo "Running flake8 with bugbear..."
        flake8 FleetGitOpsUploader/FleetGitOpsUploader.py
        echo "✅ Flake8 + bugbear passed"
        
    - name: Validate YAML formatting
      run: |
        echo "Checking YAML files..."
        python -c "
        import yaml
        import sys
        import glob
        
        files = glob.glob('**/*.recipe.yaml', recursive=True)
        
        print(f'Found {len(files)} recipe files to validate:')
        for f in sorted(files):
            print(f'  • {f}')
        print()
        
        for file in files:
            try:
                with open(file, 'r') as f:
                    yaml.safe_load(f)
                print(f'✅ {file}')
            except Exception as e:
                print(f'❌ {file}: {e}')
                sys.exit(1)
        "